### ISSUE TITLE
Linux Desktop GUI: Revisit libraries dependencies

### ISSUE THREAD

**Issue by yveszoundi** [rimerosolutions/entrusted#56]
### Background

As much as possible everything is statically linked to avoid external dependencies, but that mostly possible with command-line applications.

### Objectives

- [x]  Determine if there is some value added for having an AppImage
  - There are couple of libraries [excluded from the GUI artifact which is an AppImage](https://raw.githubusercontent.com/probonopd/AppImages/master/excludelist)
  - [Musl is not supported](https://github.com/AppImage/AppImageKit/issues/877)
- [x] Determine if the DEB and RPM packages should include explicitly dependencies such as `libXcb`, `libXfixes`, etc.
- [x] Revisit [wayland](https://wayland.freedesktop.org/) support on Linux (mostly testing efforts)
  - Are separate binaries needed?
  - Does it work seamlessly on systems without `wayland` or `x11` libraries available?

**Comment by probonopd** [comment]
> There are couple of libraries [excluded from the GUI artifact which is an AppImage](https://raw.githubusercontent.com/probonopd/AppImages/master/excludelist)

That is _one_ way to do it, _if_ you would like to use some system native libraries instead of bundling _everything_.

The _other_ way is to bundle _all_ libraries inside the AppImage, but in this case you also need to bundle a private copy of the linker (e.g., `ld-musl-x86_64.so.1`).

> Musl is not supported

That is no longer the case if you use the static runtime for your AppImage. In fact, we build it on a musl-based Alpine Linux container.

**Comment by yveszoundi** [comment]
Thank you, I'll read the documentation and get up to speed for musl support.

**Comment by probonopd** [comment]
I fear the documentation doesn't describe those things in detail (yet?).
Always keep in mind that AppImage really is just a self-mounting filesystem image that runs whatever someone has put inside it.
While it is totally possible to put "everything" inside, including `ld-musl-x86_64.so.1`, I don't remember whether anyone has written about this so far.
Hence - don't hesitate to ping me if you run into any issues.

**Comment by yveszoundi** [comment]
It seems that (for `Debian`) shared library dependencies can be generated at build time with a placeholder in the control file. 
- Initially, maybe a static list is fine. RPM libraries equivalent can be googled against what's found for Debian
- Later on, it's better to have shared libraries dependencies generated automatically for both RPM and DEB packages

### Data Collection

<details>
<summary>ldd output</summary>

```
$ ldd app/entrusted_client/target/release/entrusted-gui
linux-vdso.so.1 (0x00007ffca5bca000)
libwayland-client.so.0 => /lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007fd32ed3f000)
libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007fd32e4c0000)
libXinerama.so.1 => /lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fd32ed3a000)
libXcursor.so.1 => /lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007fd32ed2e000)
libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fd32ed26000)
libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fd32ecda000)
libpango-1.0.so.0 => /lib/x86_64-linux-gnu/libpango-1.0.so.0 (0x00007fd32ec73000)
libgobject-2.0.so.0 => /lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fd32e460000)
libcairo.so.2 => /lib/x86_64-linux-gnu/libcairo.so.2 (0x00007fd32e338000)
libpangocairo-1.0.so.0 => /lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007fd32e326000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd32e306000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd32e21f000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd32de00000)
/lib64/ld-linux-x86-64.so.2 (0x00007fd32ed67000)
libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007fd32e212000)
libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fd32e1e8000)
libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007fd32e1d3000)
libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fd32e1c6000)
libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fd32e0fe000)
libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fd32e0cd000)
libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fd32e0c4000)
libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fd32dcc6000)
libgio-2.0.so.0 => /lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007fd32daed000)
libfribidi.so.0 => /lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007fd32e0a8000)
libthai.so.0 => /lib/x86_64-linux-gnu/libthai.so.0 (0x00007fd32e09d000)
libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fd32da1e000)
libpixman-1.so.0 => /lib/x86_64-linux-gnu/libpixman-1.so.0 (0x00007fd32d973000)
libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fd32e062000)
libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007fd32e05d000)
libxcb-render.so.0 => /lib/x86_64-linux-gnu/libxcb-render.so.0 (0x00007fd32e04e000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd32e032000)
libpangoft2-1.0.so.0 => /lib/x86_64-linux-gnu/libpangoft2-1.0.so.0 (0x00007fd32d958000)
libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007fd32e02c000)
libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fd32d950000)
libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007fd32d942000)
libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fd32d8cc000)
libgmodule-2.0.so.0 => /lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007fd32d8c5000)
libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007fd32d881000)
libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fd32d855000)
libdatrie.so.1 => /lib/x86_64-linux-gnu/libdatrie.so.1 (0x00007fd32d84c000)
libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fd32d825000)
libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fd32d80d000)
libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007fd32d7ea000)
libblkid.so.1 => /lib/x86_64-linux-gnu/libblkid.so.1 (0x00007fd32d7b3000)
libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007fd32d71c000)
libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x00007fd32d70f000)
$ 
```
</details>

<details>
<summary>dpkg-shlibdeps ouput - custom formatting</summary>

```
dpkg-shlibdeps -O ../../entrusted/app/entrusted_client/target/release/entrusted-gui
dpkg-shlibdeps: warning: binaries to analyze should already be installed in their package's directory
dpkg-shlibdeps: warning: package could avoid a useless dependency if ../../entrusted/app/entrusted_client/target/release/entrusted-gui was not linked against libwayland-client.so.0 (it uses none of the library's symbols)
dpkg-shlibdeps: warning: package could avoid a useless dependency if ../../entrusted/app/entrusted_client/target/release/entrusted-gui was not linked against libfontconfig.so.1 (it uses none of the library's symbols)
shlibs:Depends=libc6 (>= 2.34), 
libcairo2 (>= 1.6.0), 
libfontconfig1 (>= 2.12.6), 
libgcc-s1 (>= 4.2), 
libglib2.0-0 (>= 2.12.0), 
libpango-1.0-0 (>= 1.44.3), 
libpangocairo-1.0-0 (>= 1.14.0), 
libwayland-client0 (>= 1.0.2), 
libx11-6, 
libxcursor1 (>> 1.1.2), 
libxfixes3, 
libxinerama1 (>= 2:1.1.4)
```
</details>

### Linux Wayland notes

When the GUI is compiled with `wayland` support, the `libwayland-client0` library is required regardless of whether the user is running `x11` or `wayland`. [It's possible to further customize wayland support](https://fltk-rs.github.io/fltk-book/FAQ.html?highlight=wayland#are-there-any-environment-variables-which-can-affect-the-build-or-behavior), but we don't.

This seems to be reasonable instead of creating separate binaries, such as:
- `linux-exe-with-x11-support`
- `linux-exe-with-wayland-support`
- `linux-exe-with-both-x11-and-wayland-support`

### References

- https://unix.stackexchange.com/questions/521030/specifying-depends-correctly-in-debian-control-file
- https://forums.debian.net/viewtopic.php?t=85790
- https://stackoverflow.com/questions/44429179/debian-control-file-dependencies-for-a-program-which-depends-on-libcurl-so-libs

**Comment by yveszoundi** [comment]
The follow-up is to create a new ticket to update the RPM spec file and the Debian control file.
