### ISSUE TITLE
Create another CD ISO release with a smaller grub timeout value

### ISSUE THREAD

**Issue by DEFCON001** [rimerosolutions/entrusted#8]
The current ISO CD release has a 30 second grub timeout at launch, having an optional ISO release that has a small or 0 timeout value so that it launches straight away would be very useful for when packaging it as an application. This is an issue with the flatpak being developed for this app: https://github.com/axtloss/flatpaks/tree/main/com.github.rimerosolutions.entrusted

**Comment by axtloss** [comment]
This is also really useful for running the live iso headless, with no way of controlling the VM/grub

**Comment by yveszoundi** [comment]
That is reasonable and thanks for looking into `flatpak` packaging. 

I changed the timeout to 2 seconds and updated the [latest ISO image](https://github.com/rimerosolutions/entrusted/releases/download/0.2.4/entrusted-livecd-amd64-0.2.4.iso). Please let me know if that works.

I'd rather not disable completely the timeout, as it can help with troubleshooting efforts (i.e. editing the grub command-line if there are boot issues on a specific machine).

I also do run the ISO "headless" in QEMU most of the time (`-display none`).
